server:
  port: 8080  # 원하는 포트로 변경할 수 있음 (예: 80, 443 등)

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:memo-db.cn860meg8hj0.ap-northeast-2.rds.amazonaws.com}:3306/${DB_NAME:your-database-name}
    username: ${DB_USERNAME:your-database-username}
    password: ${DB_PASSWORD:your-database-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # or validate, none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  logging:
    level:
      org.hibernate.SQL: WARN
      org.hibernate.type.descriptor.sql.BasicBinder: ERROR
