name: Kotlin Lint Check

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'corretto'# 필요한 Java 버전 설정

      - name: Install dependencies
        run: ./gradlew clean build  # Gradle 의존성 설치 및 빌드

      - name: Run Ktlint
        run: ./gradlew ktlintCheck  # Ktlint 검사 실행
